openshift:
    config:
        predictor:
            url: http://localhost:8080/predictions/ranks
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
server:
    port: 8181
logging:
     path: /logs/jiminy-html-server
     file: server.log
     level:
         root: INFO
