openshift:
    config:
        predictor:
          url: http://predictor:8080/predictions/ranks
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
server:
    port: 8778
