#Postgres persistence
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jiminy
    username: postgres
    password: root
dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8181
logging:
     path: /logs/jiminy-html-server
     file: server.log
     level:
         root: INFO
